import React, { useState } from 'react';
import { Copy, Check, Clock, RotateCcw, Edit3 } from 'lucide-react';
import toast from 'react-hot-toast';

export const OutputPanel = ({ content, agentName, isEditing, setIsEditing, editContent, setEditContent, onCopy, onApprove, onRegenerate, onSaveEdit }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(isEditing ? editContent : content);
    setCopied(true);
    toast.success('Copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };

  if (!content && !isEditing) {
    return (
      <div className="bg-zinc-900 rounded-xl p-6 border border-zinc-800 h-full flex items-center justify-center">
        <div className="text-center">
          <p className="text-zinc-500 text-lg">No content generated yet</p>
          <p className="text-zinc-600 text-sm mt-2">Fill out the brief and click Generate</p>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-zinc-900 rounded-xl p-6 border border-zinc-800 h-full flex flex-col">
      <div className="flex items-center justify-between mb-4">
        <span className="text-sm text-amber-500">Generated by {agentName}</span>
      </div>

      <div className="flex-1 bg-zinc-800 rounded-lg p-6 overflow-y-auto">
        {isEditing ? (
          <textarea
            value={editContent}
            onChange={(e) => setEditContent(e.target.value)}
            className="w-full h-full bg-transparent text-zinc-200 resize-none focus:outline-none"
          />
        ) : (
          <pre className="text-zinc-200 whitespace-pre-wrap font-sans">{content}</pre>
        )}
      </div>

      <div className="flex gap-3 mt-4">
        <button
          onClick={handleCopy}
          className="flex items-center gap-2 px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-500 rounded-lg transition-all"
        >
          {copied ? <Check size={16} className="text-emerald-500" /> : <Copy size={16} />}
          {copied ? 'Copied' : 'Copy'}
        </button>

        <button
          onClick={onApprove}
          className="flex items-center gap-2 px-4 py-2 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-500 rounded-lg transition-all"
        >
          <Clock size={16} />
          Approve & Schedule
        </button>

        <button
          onClick={onRegenerate}
          className="flex items-center gap-2 px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-500 rounded-lg transition-all"
        >
          <RotateCcw size={16} />
          Regenerate
        </button>

        <button
          onClick={() => {
            if (isEditing) {
              onSaveEdit();
            } else {
              setEditContent(content);
              setIsEditing(true);
            }
          }}
          className="flex items-center gap-2 px-4 py-2 bg-amber-500/10 hover:bg-amber-500/20 text-amber-500 rounded-lg transition-all"
        >
          <Edit3 size={16} />
          {isEditing ? 'Save' : 'Edit'}
        </button>
      </div>
    </div>
  );
};