// Mock sync opportunity feed — replace with Vitrina AI / music-sup feed later.

export const COMPOSER_GENRES = ['Drama', 'Horror / Thriller', 'Action / Adventure', 'Documentary', 'Comedy', 'Animation', 'Romance', 'Sci-Fi'];
export const COMPOSER_PLATFORMS = ['Netflix', 'HBO Max', 'Hulu', 'Apple TV+', 'Amazon Prime', 'Theatrical', 'Festival Circuit', 'Indie Streamer'];
export const COMPOSER_BUDGETS = [
  { id: 'micro', label: 'Micro', range: '< $5K' },
  { id: 'low',   label: 'Low',   range: '$5K – $25K' },
  { id: 'mid',   label: 'Mid',   range: '$25K – $100K' },
  { id: 'high',  label: 'High',  range: '$100K+' },
];

export const COMPOSER_PROJECT_STAGES = ['Pitching', 'In Consideration', 'Contract', 'Scoring', 'Delivered', 'Archived'];

export const composerOpportunitiesMock = [
  {
    id: 'opp-001',
    title: 'Quiet Acres',
    platform: 'Indie Streamer',
    genre: 'Drama',
    style: 'Acoustic + minimal strings; Iowa rural realism',
    budget: 'low',
    deadline: '2026-05-10',
    description: '$250K indie drama. Need a composer who can work with natural ambience and restraint.',
    contact: 'Heartland Pictures · music@heartlandpics.com',
  },
  {
    id: 'opp-002',
    title: 'Frozen Territory',
    platform: 'Festival Circuit',
    genre: 'Documentary',
    style: 'Arctic ambient; processed field recordings welcome',
    budget: 'micro',
    deadline: '2026-05-05',
    description: 'Climate documentary shot in Alaska. Temp from Jóhann Jóhannsson / Hildur Guðnadóttir.',
    contact: 'Arctic North Docs · scoring@arcticnorth.co',
  },
  {
    id: 'opp-003',
    title: 'Ravenwood S2',
    platform: 'Hulu',
    genre: 'Horror / Thriller',
    style: 'Dark orchestral; tension-driven motifs',
    budget: 'high',
    deadline: '2026-05-20',
    description: '10-episode supernatural drama S2 returning — seeking additional composer for split-episode workload.',
    contact: 'Hollow Ground Studios · music-sup@hollowground.tv',
  },
  {
    id: 'opp-004',
    title: 'Summer Heat',
    platform: 'Theatrical',
    genre: 'Comedy',
    style: 'Upbeat Latin-influenced; 80s funk cues',
    budget: 'mid',
    deadline: '2026-04-30',
    description: 'Beach-town comedy feature. Fun, propulsive, genre-leaning score.',
    contact: 'Driftline Films · hello@driftline.co',
  },
  {
    id: 'opp-005',
    title: 'Midnight Runway',
    platform: 'Apple TV+',
    genre: 'Drama',
    style: 'Fashion-world pulse; half-time electronic',
    budget: 'high',
    deadline: '2026-06-01',
    description: 'High-fashion thriller. Electronic-leaning score. Reference: Reznor/Ross, Mica Levi.',
    contact: 'Shadowline Entertainment · supervisor@shadowline.tv',
  },
  {
    id: 'opp-006',
    title: 'Carbon Footprint',
    platform: 'Festival Circuit',
    genre: 'Drama',
    style: 'Minimalist; synth + chamber strings',
    budget: 'low',
    deadline: '2026-05-15',
    description: 'Eco-thriller. Temp from Emptyset, Oneohtrix Point Never.',
    contact: 'Driftline Films · hello@driftline.co',
  },
  {
    id: 'opp-007',
    title: 'Samsung Galaxy Launch',
    platform: 'Theatrical',
    genre: 'Action / Adventure',
    style: 'Epic cinematic trailer cue; hybrid orchestral',
    budget: 'mid',
    deadline: '2026-05-12',
    description: 'Global commercial. 60/30/15 cut-downs required. Fast turnaround.',
    contact: 'Prism Creative · music@prismcreative.co',
  },
  {
    id: 'opp-008',
    title: 'Last Light',
    platform: 'Amazon Prime',
    genre: 'Sci-Fi',
    style: 'Cold futurism; texture over melody',
    budget: 'high',
    deadline: '2026-06-10',
    description: 'Sci-fi feature with strong auteur voice. Synth-forward. 70 minutes of score.',
    contact: 'Horizon Nine · composer@horizon9.studio',
  },
  {
    id: 'opp-009',
    title: 'Pitch Perfect Short',
    platform: 'Festival Circuit',
    genre: 'Animation',
    style: 'Playful; small ensemble; live strings',
    budget: 'micro',
    deadline: '2026-05-03',
    description: '12-minute animated short. Student-adjacent. Credit + festival-run fee.',
    contact: 'Undergrad Animation · submit@undergradanim.org',
  },
  {
    id: 'opp-010',
    title: 'Southern Cross',
    platform: 'HBO Max',
    genre: 'Documentary',
    style: 'Nashville roots + modern production',
    budget: 'mid',
    deadline: '2026-05-25',
    description: '8-episode music docuseries. Composer needed for interstitials + title theme.',
    contact: 'Mile Marker Media · music@milemarker.media',
  },
];
