// Mock job listings — replace this file with a real ProductionHUB / ProductionBeast
// API feed when available. Schema kept intentionally flat for easy swap.

export const CREW_ROLES = [
  'Director of Photography',
  '1st AD',
  '2nd AD',
  'Gaffer',
  'HMU',
  'Sound Mixer',
  'Production Designer',
  'Costume Designer',
  'VFX/SFX',
  'PA',
  'Other',
];

export const UNION_STATUSES = ['IATSE', 'Non-Union', 'Either'];

export const PROJECT_TYPES = ['Feature', 'TV Series', 'Commercial', 'Short', 'Doc'];

export const BUDGET_TIERS = [
  { id: 'micro', label: 'Micro', range: '< $50K' },
  { id: 'low',   label: 'Low',   range: '$50K – $500K' },
  { id: 'mid',   label: 'Mid',   range: '$500K – $5M' },
  { id: 'high',  label: 'High',  range: '$5M+' },
];

export const crewJobsMock = [
  {
    id: 'job-001',
    title: 'Untitled Anthology Horror',
    company: 'Neon Grave Pictures',
    role: 'Director of Photography',
    location: 'Atlanta, GA',
    union: 'Non-Union',
    type: 'Feature',
    budget: 'mid',
    shootDates: 'Jun 10 – Jul 22, 2026',
    postedDaysAgo: 2,
    description: 'Character-driven horror anthology — three interlocking stories. Prefer DP with anamorphic experience.',
    applyUrl: 'https://productionhub.com/jobs/neon-grave-dp',
  },
  {
    id: 'job-002',
    title: 'Ravenwood (Season 2)',
    company: 'Hollow Ground Studios',
    role: '1st AD',
    location: 'Albuquerque, NM',
    union: 'IATSE',
    type: 'TV Series',
    budget: 'high',
    shootDates: 'Jul 1 – Nov 30, 2026',
    postedDaysAgo: 4,
    description: '10-episode supernatural drama returning for S2. IATSE. Need strong scheduler with VFX-heavy episode experience.',
    applyUrl: 'https://productionhub.com/jobs/ravenwood-s2-1ad',
  },
  {
    id: 'job-003',
    title: 'Frozen Territory',
    company: 'Arctic North Docs',
    role: 'Sound Mixer',
    location: 'Fairbanks, AK',
    union: 'Non-Union',
    type: 'Doc',
    budget: 'low',
    shootDates: 'May 20 – Jun 12, 2026',
    postedDaysAgo: 1,
    description: 'Verite climate-change documentary. Cold-weather field experience required. Boom + 2 lavs min.',
    applyUrl: 'https://productionhub.com/jobs/frozen-territory-sound',
  },
  {
    id: 'job-004',
    title: 'Summer Heat (Pepsi spot)',
    company: 'Nimble Agency',
    role: 'HMU',
    location: 'Los Angeles, CA',
    union: 'Either',
    type: 'Commercial',
    budget: 'mid',
    shootDates: 'May 5 – May 7, 2026',
    postedDaysAgo: 3,
    description: '3-day commercial shoot. Bright-summer look. Must have proven beauty + sweat-effect work.',
    applyUrl: 'https://productionhub.com/jobs/summer-heat-hmu',
  },
  {
    id: 'job-005',
    title: 'Carbon Footprint',
    company: 'Driftline Films',
    role: 'Production Designer',
    location: 'Portland, OR',
    union: 'Non-Union',
    type: 'Feature',
    budget: 'low',
    shootDates: 'Aug 1 – Sep 15, 2026',
    postedDaysAgo: 6,
    description: '$300K eco-thriller. Practical locations + 4 build sets. Sustainable materials workflow a plus.',
    applyUrl: 'https://productionhub.com/jobs/carbon-footprint-pd',
  },
  {
    id: 'job-006',
    title: 'The Lighthouse Keeper',
    company: 'Saltwater Studios',
    role: 'Gaffer',
    location: 'Rockport, MA',
    union: 'IATSE',
    type: 'Feature',
    budget: 'mid',
    shootDates: 'Sep 10 – Oct 25, 2026',
    postedDaysAgo: 5,
    description: 'Period drama, heavy practicals, night exteriors on the coast. IATSE Local 481.',
    applyUrl: 'https://productionhub.com/jobs/lighthouse-keeper-gaffer',
  },
  {
    id: 'job-007',
    title: 'Campus Ghost Stories',
    company: 'Undergrad Productions',
    role: 'PA',
    location: 'Austin, TX',
    union: 'Non-Union',
    type: 'Short',
    budget: 'micro',
    shootDates: 'May 1 – May 3, 2026',
    postedDaysAgo: 1,
    description: 'Student-adjacent short. Fast-paced indie. Transpo + set PA. Gas + food covered, credit + reel footage.',
    applyUrl: 'https://productionhub.com/jobs/campus-ghost-pa',
  },
  {
    id: 'job-008',
    title: 'Midnight Runway',
    company: 'Shadowline Entertainment',
    role: 'Costume Designer',
    location: 'New York, NY',
    union: 'IATSE',
    type: 'Feature',
    budget: 'high',
    shootDates: 'Oct 10 – Dec 20, 2026',
    postedDaysAgo: 8,
    description: 'High-fashion thriller. Need designer with ready-to-wear + editorial experience. Local 764.',
    applyUrl: 'https://productionhub.com/jobs/midnight-runway-cd',
  },
  {
    id: 'job-009',
    title: 'Exit Velocity',
    company: 'Apogee VFX',
    role: 'VFX/SFX',
    location: 'Vancouver, BC',
    union: 'Non-Union',
    type: 'Feature',
    budget: 'mid',
    shootDates: 'Jul 15 – Sep 30, 2026',
    postedDaysAgo: 3,
    description: 'Practical-first sci-fi thriller. On-set SFX coordinator with explosives + atmospheric background.',
    applyUrl: 'https://productionhub.com/jobs/exit-velocity-vfx',
  },
  {
    id: 'job-010',
    title: 'Southern Cross (Docuseries)',
    company: 'Mile Marker Media',
    role: '2nd AD',
    location: 'Nashville, TN',
    union: 'Non-Union',
    type: 'TV Series',
    budget: 'mid',
    shootDates: 'Jun 15 – Aug 30, 2026',
    postedDaysAgo: 7,
    description: '8-episode music docuseries. Heavy talent wrangling + concert coverage. Music-industry comfort required.',
    applyUrl: 'https://productionhub.com/jobs/southern-cross-2ad',
  },
  {
    id: 'job-011',
    title: 'Quiet Acres',
    company: 'Heartland Pictures',
    role: 'Director of Photography',
    location: 'Des Moines, IA',
    union: 'Non-Union',
    type: 'Feature',
    budget: 'low',
    shootDates: 'Sep 1 – Oct 15, 2026',
    postedDaysAgo: 10,
    description: '$250K quiet-realism drama. Natural light + long takes. Reel must include rural exteriors.',
    applyUrl: 'https://productionhub.com/jobs/quiet-acres-dp',
  },
  {
    id: 'job-012',
    title: 'Samsung Galaxy Launch',
    company: 'Prism Creative',
    role: '1st AD',
    location: 'Seoul, South Korea (travel from US)',
    union: 'Either',
    type: 'Commercial',
    budget: 'high',
    shootDates: 'Jun 3 – Jun 10, 2026',
    postedDaysAgo: 2,
    description: '6-day global commercial. Must be US-based with valid passport. Fluent English; Korean helpful not required.',
    applyUrl: 'https://productionhub.com/jobs/samsung-launch-1ad',
  },
];
